In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving pricess.csv to pricess.csv


In [ ]:
df=pd.read_csv("pricess.csv")
df

id  number_of_bedrooms  number_of_bathrooms  living area  \
0      6762810145                   5                 2.50         3650   
1      6762810635                   4                 2.50         2920   
2      6762810998                   5                 2.75         2910   
3      6762812605                   4                 2.50         3310   
4      6762812919                   3                 2.00         2710   
...           ...                 ...                  ...          ...   
14615  6762830250                   2                 1.50         1556   
14616  6762830339                   3                 2.00         1680   
14617  6762830618                   2                 1.00         1070   
14618  6762830709                   4                 1.00         1030   
14619  6762831463                   3                 1.00          900   

       lot area    Price  
0          9050  2380000  
1          4000  1400000  
2          9480  1200000  
3         42998   838000  
4          4500   805000  
...         ...      ...  
14615     20000   221700  
14616      7000   219200  
14617      6120   209000  
14618      6621   205000  
14619      4770   146000  

[14620 rows x 6 columns]

from matplotlib import pyplot as plt
df['id'].plot(kind='hist', bins=20, title='id')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['number_of_bedrooms'].plot(kind='hist', bins=20, title='number_of_bedrooms')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['number_of_bathrooms'].plot(kind='hist', bins=20, title='number_of_bathrooms')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['living area'].plot(kind='hist', bins=20, title='living area')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='id', y='number_of_bedrooms', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='number_of_bedrooms', y='number_of_bathrooms', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='number_of_bathrooms', y='living area', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='living area', y='lot area', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['id'].plot(kind='line', figsize=(8, 4), title='id')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['number_of_bedrooms'].plot(kind='line', figsize=(8, 4), title='number_of_bedrooms')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['number_of_bathrooms'].plot(kind='line', figsize=(8, 4), title='number_of_bathrooms')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['living area'].plot(kind='line', figsize=(8, 4), title='living area')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
reg=linear_model.LinearRegression()
reg.fit(df[['lot area','number_of_bedrooms','number_of_bathrooms']],df.Price)

LinearRegression()

In [ ]:
reg.coef_

array([3.84093950e-01, 1.99216579e+04, 2.39915692e+05])

In [ ]:
reg.intercept_

-45107.46491433133

In [ ]:
reg.predict([[3000,3,2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([495641.17509916])

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1235117.86279857])

In [ ]:
k=int(input("Enter the area:"))
l=int(input("Enter the number of bedrooms:"))
m=int(input("Enter the number of bathrooms:"))
reg.predict([[k,l,m]])

Enter the area:4000
Enter the number of bedrooms:5
Enter the number of bathrooms:3


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([775784.27706909])